#!/usr/bin/env python3
"""Install Nexus as a normal Linux desktop app.

Creates a launcher script in ~/.local/bin and a .desktop entry in
~/.local/share/applications so you can open Nexus from your applications menu
or run it by typing `nexus` in a terminal.
"""

from __future__ import annotations

import argparse
import datetime
import os
import shutil
import stat
import subprocess
import sys
from pathlib import Path


_WRAPPER_MARKER = "Nexus desktop launcher -- auto-generated by install.py"


def ensure_icon(desktop_dir: Path) -> Path:
    icon_source = desktop_dir / "assets" / "nexus-icon.png"
    if not icon_source.exists():
        import generate_icon

        generate_icon.main()
    return icon_source


def _is_generated_wrapper(path: Path) -> bool:
    try:
        return _WRAPPER_MARKER in path.read_text(encoding="utf-8")
    except OSError:
        return False


def install(*, force: bool = False) -> None:
    desktop_dir = Path(__file__).resolve().parent
    project_root = desktop_dir.parent

    venv_python = desktop_dir / "venv" / "bin" / "python3"
    if not venv_python.exists():
        raise SystemExit(
            "Could not find the Nexus virtual environment.\n"
            "Please run first:\n"
            "  cd desktop\n"
            "  python3 -m venv venv\n"
            "  source venv/bin/activate\n"
            "  pip install -r requirements.txt"
        )

    home = Path.home()
    bin_dir = home / ".local" / "bin"
    applications_dir = home / ".local" / "share" / "applications"
    app_data_dir = home / ".local" / "share" / "nexus"

    bin_dir.mkdir(parents=True, exist_ok=True)
    applications_dir.mkdir(parents=True, exist_ok=True)
    app_data_dir.mkdir(parents=True, exist_ok=True)

    icon_source = ensure_icon(desktop_dir)
    icon_path = app_data_dir / "nexus-icon.png"
    if icon_source.exists():
        icon_path.write_bytes(icon_source.read_bytes())

    # Wrapper script that activates the venv and launches Nexus.
    wrapper = bin_dir / "nexus"
    if wrapper.exists() and not _is_generated_wrapper(wrapper) and not force:
        raise SystemExit(
            f"{wrapper} already exists and does not look like a Nexus wrapper.\n"
            "Run the uninstaller first: python uninstall.py\n"
            "Or re-run with --force to overwrite it."
        )

    if wrapper.exists():
        backup_suffix = datetime.datetime.now().strftime("%Y%m%d-%H%M%S")
        backup = wrapper.with_suffix(f".backup.{backup_suffix}")
        shutil.copy2(wrapper, backup)
        print(f"Existing {wrapper} backed up to {backup}")

    wrapper_content = (
        "#!/usr/bin/env bash\n"
        f"# {_WRAPPER_MARKER}\n"
        f"cd {desktop_dir} || exit 1\n"
        "source venv/bin/activate\n"
        "exec python3 -m nexus \"$@\"\n"
    )
    wrapper.write_text(wrapper_content)
    wrapper.chmod(wrapper.stat().st_mode | stat.S_IEXEC)

    # .desktop entry so the app shows up in the applications menu.
    desktop_file = applications_dir / "nexus.desktop"
    desktop_content = (
        "[Desktop Entry]\n"
        "Type=Application\n"
        "Name=Nexus\n"
        "Comment=Privacy-first local voice assistant\n"
        f"Exec={wrapper}\n"
        f"Icon={icon_path}\n"
        "Terminal=false\n"
        "Categories=Utility;Audio;Network;\n"
        "StartupNotify=true\n"
    )
    desktop_file.write_text(desktop_content)

    # Refresh the desktop menu database if the tool is available.
    print("Refreshing applications menu...")
    try:
        subprocess.run(
            ["update-desktop-database", str(applications_dir)],
            check=False,
            stdout=subprocess.DEVNULL,
            stderr=subprocess.DEVNULL,
        )
    except FileNotFoundError:
        print("(update-desktop-database not found; you may need to log out and back in for the menu to appear)")

    print(f"Installed Nexus launcher to {wrapper}")
    print(f"Installed menu entry to {desktop_file}")
    print(f"Icon installed at {icon_path}")
    print("\nYou can now:")
    print("  - Type 'nexus' in a terminal")
    print("  - Search for 'Nexus' in your applications menu")
    print("\nIf ~/.local/bin is not on your PATH, log out and back in, or run:")
    print("  export PATH=\"$HOME/.local/bin:$PATH\"")


def _parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Install Nexus as a desktop app")
    parser.add_argument(
        "--force",
        action="store_true",
        help="Overwrite an existing non-Nexus file at ~/.local/bin/nexus",
    )
    return parser.parse_args()


if __name__ == "__main__":
    args = _parse_args()
    try:
        install(force=args.force)
    except SystemExit as exc:
        sys.exit(exc)
    except Exception as exc:  # pragma: no cover - installer feedback
        print(f"Installation failed: {exc}", file=sys.stderr)
        sys.exit(1)
