// A small curated city/country → IANA timezone map for "what time is it in
// <place>". The app has no geocoder, so the honest rule is: cities in this
// map get a real inline answer; everything else falls back to a web search.
// Accent folding happens on lookup, so "paris" and "São Paulo" both work.
String? zoneForCity(String place) {
  final key = place
      .toLowerCase()
      .replaceAll(RegExp(r'[àáâäãå]'), 'a')
      .replaceAll(RegExp(r'[èéêë]'), 'e')
      .replaceAll(RegExp(r'[ìíîï]'), 'i')
      .replaceAll(RegExp(r'[òóôöõ]'), 'o')
      .replaceAll(RegExp(r'[ùúûü]'), 'u')
      .replaceAll(RegExp(r'[ç]'), 'c')
      .replaceAll(RegExp(r'[^a-z ]'), ' ')
      .replaceAll(RegExp(r'\s+'), ' ')
      .trim();
  return _zones[key];
}

const _zones = <String, String>{
  // Cities
  'paris': 'Europe/Paris',
  'london': 'Europe/London',
  'lisbon': 'Europe/Lisbon',
  'madrid': 'Europe/Madrid',
  'barcelona': 'Europe/Madrid',
  'rome': 'Europe/Rome',
  'milan': 'Europe/Rome',
  'berlin': 'Europe/Berlin',
  'munich': 'Europe/Berlin',
  'amsterdam': 'Europe/Amsterdam',
  'brussels': 'Europe/Brussels',
  'geneva': 'Europe/Zurich',
  'zurich': 'Europe/Zurich',
  'vienna': 'Europe/Vienna',
  'prague': 'Europe/Prague',
  'warsaw': 'Europe/Warsaw',
  'stockholm': 'Europe/Stockholm',
  'oslo': 'Europe/Oslo',
  'copenhagen': 'Europe/Copenhagen',
  'helsinki': 'Europe/Helsinki',
  'athens': 'Europe/Athens',
  'istanbul': 'Europe/Istanbul',
  'moscow': 'Europe/Moscow',
  'dublin': 'Europe/Dublin',
  'edinburgh': 'Europe/London',
  'tokyo': 'Asia/Tokyo',
  'osaka': 'Asia/Tokyo',
  'kyoto': 'Asia/Tokyo',
  'seoul': 'Asia/Seoul',
  'beijing': 'Asia/Shanghai',
  'shanghai': 'Asia/Shanghai',
  'hong kong': 'Asia/Hong_Kong',
  'singapore': 'Asia/Singapore',
  'bangkok': 'Asia/Bangkok',
  'jakarta': 'Asia/Jakarta',
  'manila': 'Asia/Manila',
  'kuala lumpur': 'Asia/Kuala_Lumpur',
  'delhi': 'Asia/Kolkata',
  'mumbai': 'Asia/Kolkata',
  'bombay': 'Asia/Kolkata',
  'dubai': 'Asia/Dubai',
  'tel aviv': 'Asia/Jerusalem',
  'jerusalem': 'Asia/Jerusalem',
  'new york': 'America/New_York',
  'nyc': 'America/New_York',
  'boston': 'America/New_York',
  'washington': 'America/New_York',
  'miami': 'America/New_York',
  'atlanta': 'America/New_York',
  'chicago': 'America/Chicago',
  'houston': 'America/Chicago',
  'dallas': 'America/Chicago',
  'denver': 'America/Denver',
  'phoenix': 'America/Phoenix',
  'los angeles': 'America/Los_Angeles',
  'san francisco': 'America/Los_Angeles',
  'san diego': 'America/Los_Angeles',
  'las vegas': 'America/Los_Angeles',
  'seattle': 'America/Los_Angeles',
  'toronto': 'America/Toronto',
  'montreal': 'America/Toronto',
  'ottawa': 'America/Toronto',
  'vancouver': 'America/Vancouver',
  'mexico city': 'America/Mexico_City',
  'sao paulo': 'America/Sao_Paulo',
  'rio de janeiro': 'America/Sao_Paulo',
  'buenos aires': 'America/Argentina/Buenos_Aires',
  'santiago': 'America/Santiago',
  'lima': 'America/Lima',
  'bogota': 'America/Bogota',
  'honolulu': 'Pacific/Honolulu',
  'anchorage': 'America/Anchorage',
  'cairo': 'Africa/Cairo',
  'casablanca': 'Africa/Casablanca',
  'lagos': 'Africa/Lagos',
  'nairobi': 'Africa/Nairobi',
  'johannesburg': 'Africa/Johannesburg',
  'sydney': 'Australia/Sydney',
  'melbourne': 'Australia/Melbourne',
  'brisbane': 'Australia/Brisbane',
  'perth': 'Australia/Perth',
  'auckland': 'Pacific/Auckland',
  'wellington': 'Pacific/Auckland',
  'monaco': 'Europe/Monaco',
  // Countries / regions
  'france': 'Europe/Paris',
  'england': 'Europe/London',
  'uk': 'Europe/London',
  'britain': 'Europe/London',
  'portugal': 'Europe/Lisbon',
  'spain': 'Europe/Madrid',
  'italy': 'Europe/Rome',
  'germany': 'Europe/Berlin',
  'switzerland': 'Europe/Zurich',
  'austria': 'Europe/Vienna',
  'belgium': 'Europe/Brussels',
  'netherlands': 'Europe/Amsterdam',
  'poland': 'Europe/Warsaw',
  'sweden': 'Europe/Stockholm',
  'norway': 'Europe/Oslo',
  'denmark': 'Europe/Copenhagen',
  'finland': 'Europe/Helsinki',
  'greece': 'Europe/Athens',
  'turkey': 'Europe/Istanbul',
  'russia': 'Europe/Moscow',
  'ireland': 'Europe/Dublin',
  'scotland': 'Europe/London',
  'japan': 'Asia/Tokyo',
  'korea': 'Asia/Seoul',
  'china': 'Asia/Shanghai',
  'india': 'Asia/Kolkata',
  'thailand': 'Asia/Bangkok',
  'indonesia': 'Asia/Jakarta',
  'philippines': 'Asia/Manila',
  'malaysia': 'Asia/Kuala_Lumpur',
  'uae': 'Asia/Dubai',
  'israel': 'Asia/Jerusalem',
  'usa': 'America/New_York',
  'america': 'America/New_York',
  'canada': 'America/Toronto',
  'brazil': 'America/Sao_Paulo',
  'argentina': 'America/Argentina/Buenos_Aires',
  'chile': 'America/Santiago',
  'peru': 'America/Lima',
  'colombia': 'America/Bogota',
  'egypt': 'Africa/Cairo',
  'morocco': 'Africa/Casablanca',
  'nigeria': 'Africa/Lagos',
  'kenya': 'Africa/Nairobi',
  'south africa': 'Africa/Johannesburg',
  'australia': 'Australia/Sydney',
  'new zealand': 'Pacific/Auckland',
};